authors:
  chris:
    name: Chris Cumming
    description: Host
    avatar: https://weeklydevchat.github.io/hosts/chris.jpeg
  norm:
    name: Norman Lorrain
    description: Host
    avatar: https://weeklydevchat.github.io/hosts/norm.png
    