authors:
  chris:
    name: Chris Cumming
    description: Host
    avatar: https://weeklydevchat.com/hosts/chris.jpeg
  norm:
    name: Norman Lorrain
    description: Host
    avatar: https://weeklydevchat.com/hosts/norm.png
  omar:
    name: Omar Ashour
    description: Host
    avatar: https://weeklydevchat.com/hosts/omar.png
