authors:
  chris:
    name: Chris Cumming
    description: Host
    avatar: /hosts/chris.webp
  norm:
    name: Norman Lorrain
    description: Host
    avatar: /hosts/norm.webp
  omar:
    name: Omar Ashour
    description: Host
    avatar: /hosts/omar.webp
